%% Copyright (C) 2016 Achim D. Brucker, https://www.brucker.ch
%%
%% License:
%%   This program can be redistributed and/or modified under the terms
%%   of the LaTeX Project Public License Distributed from CTAN
%%   archives in directory macros/latex/base/lppl.txt; either
%%   version 1 of the License, or any later version.
%%   OR
%%   The 2-clause BSD-style license.
%%
\NeedsTeXFormat{LaTeX2e}[1994/06/01]
\ProvidesClass{tuos-poster}%
  [2016/08/20 v1.1  LaTeX poster class following the cooperate design of The University of Sheffield]
\RequirePackage{ifthen}
\LoadClassWithOptions{beamer}[]
\ProcessOptions\relax
\usetheme{tuos-poster}
\endinput
